print('****문제1****')
cash=5000
print('cash='+str(cash)+'원')
candy=120
print('candy='+str(candy)+'원')
total=cash//candy
print('total='+str(total)+'개')
print()
print('****문제2_1****')
precious='부모님,친구들,핸드폰,노트북,돈,미래,열정'
print('precious',precious)
print('@@@내게 소중한 것 7가지?')
print(precious)
print()
print('****문제2_2****')
a='부모님'
b='친구들'
c='핸드폰'
d='노트북'
e='돈'
f='미래'
g='열정'
print('a',a)
print('b',b)
print("c",c)
print('d',d)
print('e',e)
print('f',f)
print('g',g)
print('@@@내게 소중한 것 7가지?')
print(a,b,c,d,e,f,g)
print()
print('****문제3****')
attendance=25
chicken=attendance*3
water=attendance*1
pizza=attendance*4
print('chicken=',chicken)
print('water=',water)
print('pizza=',pizza)
