print('***문제1***')
cash=5000
print('cash='+str(cash))
candy=120
print('cash='+str(candy))
total=cash//candy
print('total='+str(total))
print()
print('***문제2-1***')
msg='가족,돈,명예,친구들,정직,신뢰,행복'
print('msg',msg)
print('@@@내게 소중한 것 7가지?')
print(msg)
print()
print('***문제2-2***')
a='가족'
b='돈'
c='명예'
d='친구들'
e='정직'
f='신뢰'
g='행복'
print('a',a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)
print('f',f)
print('g',g)
print('@@@내게 소중한 것 7가지')
print(a,b,c,d,e,f,g)
print()
print('***문제3***')
attendance=25
friedchicken=attendance*3
water=attendance*1
pizza=attendance*4
print('friedchicken=',friedchicken)
print('water=',water)
print('pizza=',pizza)
      
