# Compiler: g++
CXX = g++
# Flags: C++14 standard
CPPFLAGS += -std=c++14
# Libmath
#LIBS += -lm

# making the executable from object file
mp3_20161603:
	$(CXX) $(CPPFLAGS) mp3_20161603.cpp -o mp3_20161603 $(LIBS)

clean:
	rm mp3_20161603
