/**
 * CSE3040 HW2
 * Level011.java
 * Purpose: Prints out fibonacci sequence
 *
 * @version 1.0 Nov. 4. 2019.
 * @author MJ Shin
 */


/**
 * General interface for implementing IntSequence
 */
interface IntSequence {
    /**
     * Returns whether the sequence has next element
     * @return true if instance is not empty, false if empty.
     */
    public abstract boolean hasNext();

    /**
     * Returns next value in the sequence
     * @return The next value in int
     */
    public abstract int next();
}

/**
 * Class for generating fibonacci sequence.
 */
class FibonacciSequence implements IntSequence{
    private int now, next;

    // Constructor sets next to 1, and now to 0
    public FibonacciSequence() {
        this.next = 1;
        this.now = 0;
    }

    // Fibonacci sequence always have next item.
    @Override
    public boolean hasNext() { return true; }

    // Next item is generated by adding now and next instance variables.
    @Override
    public int next() {
        int ret;
        ret = this.now;
        this.now = this.next;
        this.next += ret;
        return ret;
    }
}

/**
 * Main class
 */
public class Level011 {
    public static void main(String[] args) {
        IntSequence seq = new FibonacciSequence();
        for(int i=0; i<20; i++) {
            if(!seq.hasNext())
                break;
            System.out.print(seq.next() + " ");
        }
        System.out.println("");
    }
}
