print("***** 문제 1 *****")
precious1=input("소중한 것?")
precious2=input("소중한 것?")
precious3=input("소중한 것?")
precious4=input("소중한 것?")
precious5=input("소중한 것?")
precious6=input("소중한 것?")
precious7=input("소중한 것?")
print("@@@내게 소중한 것 7가지")
print(precious1, precious2, precious3, precious4, precious5, precious6, precious7)
print()
print("***** 문제 2 *****")
n1, n2, n3, n4, n5, n6, n7=input("내게 소중한 것?").split()
print("="*12)
print("소중한 것 7가지")
print("="*12)
print(n1)
print(n2)
print(n3)
print(n4)
print(n5)
print(n6)
print(n7)
print()
print(n1, n2, n3, n4, n5, n6, n7)
print()
print("***** 문제 3 *****")
msg1, msg2, msg3, msg4, msg5, msg6 = ("오래참고 온유하며 자랑하지아니하며 교만하지아니하며 무례히행하지아니하며 자기의유익을구하지아니하며").split()
print("사랑은 %s" %msg1)
print("사랑은 %s" %msg2)
print("사랑은 %s" %msg3)
print("사랑은 %s" %msg4)
print("사랑은 %s" %msg5)
print("사랑은 %s" %msg6)
print()
print("***** 문제4 *****")
print("사랑은 {}".format(msg1))
print("사랑은 {}".format(msg2))
print("사랑은 {}".format(msg3))
print("사랑은 {}".format(msg4))
print("사랑은 {}".format(msg5))
print("사랑은 {}".format(msg6))
print()
print("***** 문제 5 *****")
dateToday = input("Today Date??")
year, month, day = dateToday.split("/")
print("{}".format(year)+"년", "{}".format(month)+"월", "{}".format(day)+"일")
