print("20190181 박종원 실습 5 \n \n")

print("\n"+"*"*5,"문제 1","*"*5)
p1=input("소중한 것?")
p2=input("소중한 것?")
p3=input("소중한 것?")
p4=input("소중한 것?")
p5=input("소중한 것?")
p6=input("소중한 것?")
p7=input("소중한 것?")
print("@@@내게 소중한 것 7가지")
print(p1,p2,p3,p4,p5,p6,p7)

print("\n"+"*"*5,"문제 2","*"*5)
p21,p22,p23,p24,p25,p26,p27=input("내게 소중한 것? ").split()
print("="*12+"\n내게 소중한 것 7가지\n"+"="*12)
print("%s\n%s\n%s\n%s\n%s\n%s\n%s\n " %(p21,p22,p23,p24,p25,p26,p27))
print(p21,p22,p23,p24,p25,p26,p27)

print("\n"+"*"*5,"문제 3","*"*5)
msg="오래참고 온유하며 자랑하지아니하며 교만하지아니하며 무례히행하지아니하며 자기의유익을구하지아니하며"
msg1,msg2,msg3,msg4,msg5,msg6=msg.split()
print("사랑은 %s" %msg1)
print("사랑은 %s" %msg2)
print("사랑은 %s" %msg3)
print("사랑은 %s" %msg4)
print("사랑은 %s" %msg5)
print("사랑은 %s" %msg6)

print("\n"+"*"*5,"문제 4","*"*5)
print("사랑은 {}".format(msg1))
print("사랑은 {}".format(msg2))
print("사랑은 {}".format(msg3))
print("사랑은 {}".format(msg4))
print("사랑은 {}".format(msg5))
print("사랑은 {}".format(msg6))

print("\n"+"*"*5,"문제 5","*"*5)
dateToday=input("Today Date??")
year,month,day=dateToday.split("/")
print("{}년 {}월 {}일".format(year, month, day))
