print('*********문제 1*********')
print()
v1=input('소중한 것?')
v2=input('소중한 것?')
v3=input('소중한 것?')
v4=input('소중한 것?')
v5=input('소중한 것?')
v6=input('소중한 것?')
v7=input('소중한 것?')
print('@@@내게 소중한 것 7가지')
print(v1,v2,v3,v4,v5,v6,v7)
print()
print('*********문제 2*********')
print()
p1,p2,p3,p4,p5,p6,p7=input('내게 소중한 것?').split()
print('===============')
print('소중한 것 7가지')
print('===============')
print(p1)
print(p2)
print(p3)
print(p4)
print(p5)
print(p6)
print(p7)
print(p1,p2,p3,p4,p5,p6,p7)
print()
print('*********문제 3*********')
print()
msg='오래참고 온유하며 자랑하지아니하며 교만하지아니하며 무례히행하지아니하며 자기의유익을구하지아니하며'
m1,m2,m3,m4,m5,m6=msg.split()
print('사랑은 %s'%m1)
print('사랑은 %s'%m2)
print('사랑은 %s'%m3)
print('사랑은 %s'%m4)
print('사랑은 %s'%m5)
print('사랑은 %s'%m6)
print()
print('*********문제 4*********')
print()
print('사랑은 {}'.format(m1))
print('사랑은 {}'.format(m2))
print('사랑은 {}'.format(m3))
print('사랑은 {}'.format(m4))
print('사랑은 {}'.format(m5))
print('사랑은 {}'.format(m6))
print()
print('*********문제 5*********')
print()
dateToday=input('Today Date??')
year,month,day=dateToday.split('/')
print('{}년 {}월 {}일'.format(year,month,day))
