print("*****문제1*****")
a1=input("소중한 것?")
a2=input("소중한 것?")
a3=input("소중한 것?")
a4=input("소중한 것?")
a5=input("소중한 것?")
a6=input("소중한 것?")
a7=input("소중한 것?")
print("@@@내게 소중한 것 7가지")
print(a1,a2,a3,a4,a5,a6,a7)
print()
print("*****문제2*****")
b1,b2,b3,b4,b5,b6,b7=input("내게 소중한 것?").split()
print("="*12);print("소중한 것 7가지");print("="*12)
print(b1);print(b2);print(b3);print(b4);print(b5);print(b6);print(b7)
print()
print(b1,b2,b3,b4,b5,b6,b7)
print()
print("*****문제3*****")
msg="오래참고 온유하며 자랑하지아니하며 교만하지아니하며 무례히행하지아니하며 자기의유익을구하지아니하며"
msg1,msg2,msg3,msg4,msg5,msg6=msg.split()
print("사랑은 %s" %msg1)
print("사랑은 %s" %msg2)
print("사랑은 %s" %msg3)
print("사랑은 %s" %msg4)
print("사랑은 %s" %msg5)
print("사랑은 %s" %msg6)
print()
print("*****문제4*****")
print("사랑은 {}".format(msg1))
print("사랑은 {}".format(msg2))
print("사랑은 {}".format(msg3))
print("사랑은 {}".format(msg4))
print("사랑은 {}".format(msg5))
print("사랑은 {}".format(msg6))
print()
print("*****문제5*****")
dateToday=input("Today Date??")
year,month,day=dateToday.split('/')
print("{}년 {}월 {}일".format(year,month,day))
