print("***** 문제1 *****")
v1=input("소중한 것?")
v2=input("소중한 것?")
v3=input("소중한 것?")
v4=input("소중한 것?")
v5=input("소중한 것?")
v6=input("소중한 것?")
v7=input("소중한 것?")
print("@@@내게 소중한 것 7가지")
print(v1,v2,v3,v4,v5,v6,v7)
print()
print("***** 문제2 *****")
v1,v2,v3,v4,v5,v6,v7=input("내게 소중한 것?").split()
print("="*13);print("소중한 것 7가지");print("="*13)
print(v1)
print(v2)
print(v3)
print(v4)
print(v5)
print(v6)
print(v7)
print(v1,v2,v3,v4,v5,v6,v7)
print()
print("***** 문제3 *****")
msg="""오래참고 온유하며 자랑하지아니하며 교만하지아니하며
무례히행하지아니하며 자기의유익을구하지아니하며"""
msg1,msg2,msg3,msg4,msg5,msg6=msg.split()
print("사랑은 %s" % msg1)
print("사랑은 %s" % msg2)
print("사랑은 %s" % msg3)
print("사랑은 %s" % msg4)
print("사랑은 %s" % msg5)
print("사랑은 %s" % msg6)
print()
print("***** 문제4 *****")
print("사랑은 {}".format(msg1))
print("사랑은 {}".format(msg2))
print("사랑은 {}".format(msg3))
print("사랑은 {}".format(msg4))
print("사랑은 {}".format(msg5))
print("사랑은 {}".format(msg6))
print()
print("***** 문제5 *****")
input("Today Date??")
dayToday='2019/10/08'
year,month,day=dayToday.split("/")
print("{}년 {}월 {}일".format(year,month,day))
