print('20190069 윤형식 실습5')
print()
print('******문제1******')
var1=input('소중한 것?')
var2=input('소중한 것?')
var3=input('소중한 것?')
var4=input('소중한 것?')
var5=input('소중한 것?')
var6=input('소중한 것?')
var7=input('소중한 것?')
print('@@@내게 소중한 것 7가지')
print(var1,var2,var3,var4,var5,var6,var7)
print()
print('******문제2******')
var=input('내게 소중한 것?')
var1,var2,var3,var4,var5,var6,var7=var.split()
print('='*15)
print('내게 소중한 것?')
print('='*15)
print(var1)
print(var2)
print(var3)
print(var4)
print(var5)
print(var6)
print(var7)
print()
print(var1,var2,var3,var4,var5,var6,var7)
print()
print('*****문제3*****')
msg='오래참고 온유하며 자랑하지아니하며 교만하지아니하며 무례히행하지아니하며\
 자기의유익을구하지아니하며'
msg1,msg2,msg3,msg4,msg5,msg6=msg.split()
print('사랑은 %s'%msg1)
print('사랑은 %s'%msg2)
print('사랑은 %s'%msg3)
print('사랑은 %s'%msg4)
print('사랑은 %s'%msg5)
print('사랑은 %s'%msg6)
print()
print('*****문제4*****')
print('사랑은 {}'.format(msg1))
print('사랑은 {}'.format(msg2))
print('사랑은 {}'.format(msg3))
print('사랑은 {}'.format(msg4))
print('사랑은 {}'.format(msg5))
print('사랑은 {}'.format(msg6))
print()
print('*****문제5*****')
date=input('today date?')
year,month,day=date.split('/')
print('{}년 {}월 {}일'.format(year,month,day))
