#20190216 이정빈 실습05

print("***** 문제 1 *****")
pre1 = input("소중한 것?")
pre2 = input("소중한 것?")
pre3 = input("소중한 것?")
pre4 = input("소중한 것?")
pre5 = input("소중한 것?")
pre6 = input("소중한 것?")
pre7 = input("소중한 것?")
print("@@@내게 소중한 것 7가지")
print(pre1, pre2, pre3, pre4, pre5, pre6, pre7)
print()

print("***** 문제 2 *****")
Msg = input("내게 소중한 것? ")
Msg1, Msg2, Msg3, Msg4, Msg5, Msg6, Msg7 = Msg.split()
print("="*12); print("소중한 것 7가지"); print("="*12)
print(Msg1)
print(Msg2)
print(Msg3)
print(Msg4)
print(Msg5)
print(Msg6)
print(Msg7)
print()
print(Msg1, Msg2, Msg3, Msg4, Msg5, Msg6, Msg7)
print()

msg = "오래참고 온유하며 자랑하지아니하며 교만하지아니하며 무례히행하지아니하며 자기의유익을구하지아니하며"
msg1, msg2, msg3, msg4, msg5, msg6 = msg.split()
print("***** 문제 3 *****")
print("사랑은 %s"%msg1)
print("사랑은 %s"%msg2)
print("사랑은 %s"%msg3)
print("사랑은 %s"%msg4)
print("사랑은 %s"%msg5)
print("사랑은 %s"%msg6)
print()

print("***** 문제 4 *****")
print("사랑은 {}".format(msg1))
print("사랑은 {}".format(msg2))
print("사랑은 {}".format(msg3))
print("사랑은 {}".format(msg4))
print("사랑은 {}".format(msg5))
print("사랑은 {}".format(msg6))
print()

print("***** 문제 5 *****")
dateToday = input("Today Date?? ")
year, month, day = dateToday.split("/")
print("{}년 {}월 {}일".format(year, month, day))
