print('20190088 이은서 실습5')
print()
print('*'*5,'문제1','*'*5)
input('소중한 것?')
input('소중한 것?')
input('소중한 것?')
input('소중한 것?')
input('소중한 것?')
input('소중한 것?')
input('소중한 것?')
print('내게 소중한 것 7가지')
print('꿈 사랑 긍정 행복 기쁨 믿음 즐거움')
print()
print('*'*5,'문제2','*'*5)
a=input('내게 소중한 것?')
print('='*16)
print('소중한 것 7가지')
print('='*16)
a1,a2,a3,a4,a5,a6,a7=a.split()
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
print(a7)
print()
print(a1,a2,a3,a4,a5,a6,a7)
print()
print('*'*5,'문제3','*'*5)
msg='오래참고 온유하며 자랑하지아니하며 교만하지아니하며 무례히행하지아니하며 자기의유익을구하지아니하며'
msg1,msg2,msg3,msg4,msg5,msg6=msg.split()
print('사랑은 %s'%msg1)
print('사랑은 %s'%msg2)
print('사랑은 %s'%msg3)
print('사랑은 %s'%msg4)
print('사랑은 %s'%msg5)
print('사랑은 %s'%msg6)
print()
print('*'*5,'문제4','*'*5)
print("사랑은 {}".format(msg1))
print("사랑은 {}".format(msg2))
print("사랑은 {}".format(msg3))
print("사랑은 {}".format(msg4))
print("사랑은 {}".format(msg5))
print("사랑은 {}".format(msg6))
print()
print('*'*5,'문제5','*'*5)
d=input('Today Date??')
year,month,day=d.split('/')
print('{}년 {}월 {}일'.format(year,month,day))






