print("20190323 이혜은 실습#5")
print()
print("***** 문제1 *****")
var1=input("소중한 것?")
var2=input("소중한 것?")
var3=input("소중한 것?")
var4=input("소중한 것?")
var5=input("소중한 것?")
var6=input("소중한 것?")
var7=input("소중한 것?")
print("@@@내게 소중한 것 7가지""")
print(var1,var2,var3,var4,var5,var6,var7)
print()
print("***** 문제2 *****")
a=input("내게 소중한 것?")
a1,a2,a3,a4,a5,a6,a7=a.split()
print("="*15)
print("소중한 것 7가지")
print("="*15)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
print(a7)
print()
print(a1,a2,a3,a4,a5,a6,a7)
print()
print("***** 문제3 *****")
msg="오래참고 온유하며 자랑하지아니하며 교만하지아니하며 \
무례히행하지아니하며 자기의유익을구하지아니하며"
msg1,msg2,msg3,msg4,msg5,msg6=msg.split()
print("사랑은 %s"%msg1)
print("사랑은 %s"%msg2)
print("사랑은 %s"%msg3)
print("사랑은 %s"%msg4)
print("사랑은 %s"%msg5)
print("사랑은 %s"%msg6)
print()
print("***** 문제4 *****")
print("사랑은 {}".format(msg1))
print("사랑은 {}".format(msg2))
print("사랑은 {}".format(msg3))
print("사랑은 {}".format(msg4))
print("사랑은 {}".format(msg5))
print("사랑은 {}".format(msg6))
print()
print("***** 문제5 *****")
dateToday=input("Today Date??")
year, month, day=dateToday.split('/')
print("{}년".format(year),"{}월".format(month),"{}일".format(day))
