print("***** 문제 1 *****")
a1=input("소중한 것?")
a2=input("소중한 것?")
a3=input("소중한 것?")
a4=input("소중한 것?")
a5=input("소중한 것?")
a6=input("소중한 것?")
a7=input("소중한 것?")
print("@@@내게 소중한 것 7가지")
print(a1, a2, a3, a4, a5, a6, a7)
print(" ")
print("***** 문제 2 *****")
ms=input("내게 소중한 것?")
ms1, ms2, ms3, ms4, ms5, ms6, ms7=ms.split()
print("="*12) ; print("소중한 것 7가지") ; print("="*12)
print(ms1)
print(ms2)
print(ms3)
print(ms4)
print(ms5)
print(ms6)
print(ms7)
print(" ")
print(ms)
print(" ")
print("***** 문제 3 *****")
msg="오래참고 온유하며 자랑하지아니하며 교만하지아니하며 \
무례히행하지아니하며 자기의유익을구하지아니하며"
msg1, msg2, msg3, msg4, msg5, msg6=msg.split()
print("사랑은 %s" %msg1)
print("사랑은 %s" %msg2)
print("사랑은 %s" %msg3)
print("사랑은 %s" %msg4)
print("사랑은 %s" %msg5)
print("사랑은 %s" %msg6)
print(" ")
print("***** 문제 4 *****")
print("사랑은 {}".format(msg1))
print("사랑은 {}".format(msg2))
print("사랑은 {}".format(msg3))
print("사랑은 {}".format(msg4))
print("사랑은 {}".format(msg5))
print("사랑은 {}".format(msg6))
print(" ")
print("***** 문제 5 *****")
dateToday=input("TodayDate??")
year, month, date=dateToday.split('/')
print("{}년 {}월 {}일".format(year, month, date))
